### PR TITLE
Use chunk_iter when adding chunk refs

### LINKED ISSUE #67: Use chunk_iter to avoid slow performance for files with many chunks
When working with datasets with a large number of chunks and requesting that their chunk information be cached in the LINDI file (e.g., by setting `num_dataset_chunks_threshold` to a very large number or None), h5py/HDF5 performance for `get_chunk_info` for getting chunk locations and offsets is terrible. This was reported here: https://github.com/h5py/h5py/issues/2117 

Since then, [h5py 3.8](https://docs.h5py.org/en/stable/whatsnew/3.8.html) was released, which adds the method `h5py.h5d.DatasetID.chunk_iter()`, which is significantly faster at retrieving chunk information. This method works only for HDF5 1.12.3 and above. Unfortunately, the latest release of h5py on PyPI (3.11.0) for Mac includes HDF5 1.12.2. Pre-built packages on Linux & Windows bundle HDF5 version 1.14.2. To use this faster method on Mac, we have to install the latest h5py from conda-forge or build it from source with HDF5 1.12.3.

Use case: [this nwb file in dandiset 000717](https://dandiarchive.org/dandiset/000717/draft/files?location=sub-R6_ses-20200206T210000_behavior%2Bophys&page=1) has just over 1 million chunks. Using the old method, getting the chunk info for the first 100 chunks takes about 15-23 seconds and the time appears to be roughly, but not exactly, linear in the number of chunks requested. If we assume it is linear, then to get chunk info for ALL chunks would take about 56 hours. Using the new method, getting the chunk info for ALL chunks takes about 1-6 seconds. The variation between 1 and 6 seconds might depend on hdf5 caching. 

I suggest we use `chunk_iter` if available and fall back to `get_chunk_info` with a warning if there are a large number of chunks. I was going to suggest using `tqdm` to monitor getting the chunks, but I think given the 1-6 second speed of the new method, it is not necessary.

```python
from tqdm import tqdm
import h5py
import timeit

url_or_path = "/Users/rly/Downloads/sub-R6_ses-20200206T210000_behavior+ophys.nwb"
with h5py.File(url_or_path, "r") as f:
    start_time = timeit.default_timer()
    h5_dataset = f["/acquisition/TwoPhotonSeries/data"]
    dsid = h5_dataset.id
    # for i in tqdm(range(100)):
    for i in range(100):
        chunk_info = dsid.get_chunk_info(i)
    
    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    print(f'Time elapsed: {elapsed_time} seconds')
```

```python
import h5py
import timeit

url_or_path = "/Users/rly/Downloads/sub-R6_ses-20200206T210000_behavior+ophys.nwb"
with h5py.File(url_or_path, "r") as f:
    start_time = timeit.default_timer()
    h5_dataset = f["/acquisition/TwoPhotonSeries/data"]
    dsid = h5_dataset.id
    stinfo = list()
    dsid.chunk_iter(stinfo.append)
    print(len(stinfo))
    print(stinfo[-1])

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    print(f'Time elapsed: {elapsed_time} seconds')
```

### PR DESCRIPTION
**Pull request by rly**
Fix #67.

I added `lindi.LindiH5ZarrStore._util._get_all_chunk_info`. 

`LindiH5ZarrStore._get_chunk_file_bytes_data` was being called in two places:
1. in `to_reference_file_system.process_dataset` in a loop over all chunks to get the chunk info for each chunk to add to the refs dict
2. by `_get_chunk_file_bytes` which is called by `__getitem__` for a single key

Because the new `chunk_iter` method returns the chunk info for all chunks and takes 1-5 seconds, it is best to use that in use case 1 above. The old `get_chunk_info` method takes about 0.2 seconds. It is best to use that for use case 2 above when a user wants to access a single key. 

TODO: if the user wants to access more than ~10 keys for a given dataset, e.g., they are requesting a large slice, then probably it would be best to use the `chunk_iter` method and cache the chunk info in `LindiH5ZarrStore`. Alternatively, we could just always run `chunk_iter` and cache the chunk info.

I tried putting a bunch of if/else branches in `LindiH5ZarrStore._get_chunk_file_bytes_data` to handle the two use cases above, but it got messy and complex. So I just created a new function `_add_chunk_info_to_refs` for use case 1 which has some of the same code as `_get_chunk_file_bytes_data`. It needs to be refactored.

This also adds `tqdm` as a dependency for showing a progress bar when iterating through many chunks. I think that is useful overall, but we could move that to an optional dependency if we think it is not so important.

@magland before I continue, can you take a look at this and let me know if I am understanding the code correctly and if the approach looks good?

TODO:
- [x] refactor redundant code
- [x] remove unnecessary chunk coordinate calculating code
- [ ] add tests, especially with HDF5 < 1.12.3 and >= 1.12.3

### CODE REVIEW

**Comment by magland** [comment]
Pushed some small changes to keep the linter happy (pyright / flake8). Passes tests now.

... continuing my review...

**Comment by magland** [comment]
@rly This all looks great

**Comment by rly** [comment]
@magland great! thanks for the look over

In https://github.com/NeurodataWithoutBorders/lindi/blob/1fc62ef070b9cb545704f69a71dad26acbdb6f7f/lindi/LindiH5ZarrStore/LindiH5ZarrStore.py#L573
when would `chunks[i]` ever be 0?

When I try to create an h5py dataset with a chunk dimension length = 0, I get an error:
```python
with h5py.File("test.h5", "w") as f:
    f.create_dataset("data", shape=(2,2,2), dtype="i4", chunks=(1,1,0))
ValueError: All chunk dimensions must be positive (all chunk dimensions must be positive)
```

**Comment by rly** [comment]
Maybe related: the line above says `chunks = zarray_dict.get("chunks", None)` but the lines below assume that `chunks` is not None. Is `chunks` always set in the zarray dict? I think Zarr always sets `chunks`. 

```python
> root = zarr.open("test.zarr", mode="w")
> data = root.create_dataset("data", shape=(0, 0), chunks=None)
> data.chunks
(1, 1)
```

**Comment by rly** [comment]
Though in Zarr, you can explicitly set the chunk dimension lengths to 0...
```python
> root = zarr.open("test.zarr", mode="w")
> data = root.create_dataset("data", shape=(0, 0), chunks=(0, 0))
> data.chunks
(0, 0)
```

**Comment by magland** [comment]
> when would `chunks[i]` ever be 0?

I have the following in comment elsewhere in the code (it should probably be pasted above this line as well):

"the shape could be zero -- for example dandiset 000559 - acquisition/depth_video/data has shape [0, 0, 0]"

I'm not sure how the shape got to be that... but you can check that dandiset.

**Comment by rly** [comment]
> "the shape could be zero -- for example dandiset 000559 - acquisition/depth_video/data has shape [0, 0, 0]"
This dataset has shape = `(0,0,0)` and the chunks = `None`.

I just removed that chunk of code and wanted to make sure I wasn't missing an unusual edge case. I think the modification would work for this dataset, but I'll add a test.

**Comment by rly** [comment]
I just updated `lindi/LindiH5ZarrStore/LindiH5ZarrStore.py` so that when writing all chunks in `to_reference_file_system`, we no longer pre-compute the names or indices of the chunks. This means `_add_chunk_info_to_refs` no longer needs a list of key names; instead we generate them based on the metadata of each chunk. This removes the need for a lot of consistency checks in `_add_chunk_info_to_refs`. The order is the same as before.

I think a progress bar is useful. Annoyingly, `dsid.get_num_chunks()` is quite slow, and this is very noticeable when the dataset is remote, so I added `_get_max_num_chunks` to replace it for the progress bar. This count includes unallocated chunks. Rarely do NWB files have unallocated chunks. But in general, it provides, at worst, an overestimate of the remaining progress.

**Comment by magland** [comment]
> I just updated `lindi/LindiH5ZarrStore/LindiH5ZarrStore.py` so that when writing all chunks in `to_reference_file_system`, we no longer pre-compute the names or indices of the chunks. This means `_add_chunk_info_to_refs` no longer needs a list of key names; instead we generate them based on the metadata of each chunk. This removes the need for a lot of consistency checks in `_add_chunk_info_to_refs`. The order is the same as before.
> 
> I think a progress bar is useful. Annoyingly, `dsid.get_num_chunks()` is quite slow, and this is very noticeable when the dataset is remote, so I added `_get_max_num_chunks` to replace it for the progress bar. This count includes unallocated chunks. Rarely do NWB files have unallocated chunks. But in general, it provides, at worst, an overestimate of the remaining progress.

This all sounds good to me.

**Review by magland — APPROVED** [review]

**Comment by magland** [comment]
@rly is the ready to get merged in yet? Is there something I can help with?

**Comment by rly** [comment]
I wanted to add some tests but let's go ahead and merge this so that we can use it in the benchmarks for the proposal. We can add tests in a separate PR.

**Comment by magland** [comment]
Okay, I just published 0.3.5 from main branch.

**Pull request merged**
