### PR TITLE
remove staging area functionality

### PR DESCRIPTION
**Pull request by magland**
@rly as we discussed, this removes all staging area functionality because this is now replaced by the writeable .lindi.tar and .lindi.d formats.

Also removed the File() class which was supposed to be a drop-in replacement for h5py.File including writing to a staging area. 

Also removed the upload() capability. That should be handled separately, IMO.

### CODE REVIEW

**Comment by oruebel** [comment]
> Also removed the File() class which was supposed to be a drop-in replacement for h5py.File including writing to a staging area.

Just wanted to clarify, is this the same as the `h5py.File` type class that is being used for reading from HDF5 files or is this a separate class that was used just for writing data to a staging area?

**Comment by magland** [comment]
> > Also removed the File() class which was supposed to be a drop-in replacement for h5py.File including writing to a staging area.
> 
> Just wanted to clarify, is this the same as the `h5py.File` type class that is being used for reading from HDF5 files or is this a separate class that was used just for writing data to a staging area?

It's confusing, sorry. The primary class for reading hdf5 files in lindi (and doing other manipulations) is LindiH5pyFile which inherits h5py.File for compatibility purposes. This lindi.File that is being removed was different. It was supposed to be a drop-in replacement for h5py.File for both reading and writing with a staging area. But now that staging area is going away and there is a different mechanism for writing, this lindi.File needs to disappear as well. Hopefully with its demise the confusion will end here. :)

**Comment by oruebel** [comment]
> Hopefully with its demise the confusion will end here. :)

That makes sense. Thank you for the clarification 👍

**Review by rly — APPROVED** [review]

**Comment by rly** [comment]
Looks good to me!

**Pull request merged**
